import {
  FAQIcon,
  HelpSupportIcon,
  HomeIcon,
  HowToPlayIcon,
  MatchIcon,
  PrivacyPolicyIcon,
  ProfileIcon,
  ReferIcon,
  RewardIcon,
  SettingsIcon,
  TermsCondition,
  TransactionIcon,
} from "./Icons";

export const footerLinks = [
  {
    title: "Home",
    icon: <HomeIcon />,
    url: "/",
  },
  {
    title: "My Matches",
    icon: <MatchIcon />,
    url: "/matches/upcoming",
  },
  {
    title: "Rewards",
    icon: <RewardIcon />,
    url: "/rewards",
  },
  {
    title: "Refer & Earn",
    icon: <ReferIcon />,
    url: "/refer-earn",
  },
  {
    title: "Profile",
    icon: <ProfileIcon />,
    url: "/profile",
  },
];

export const matchs = [
  {
    team_Q1: "RR",
    title_Q1: "Rajasthan Royals",
    logo_Q1: "/img/flags/RR.png",

    time: {
      date: "17th May",
      time: "08:00 PM",
    },

    team_Q2: "PBKS",
    title_Q2: "Punjab Kings",
    logo_Q2: "/img/flags/punjab.png",
  },
  {
    team_Q1: "RR",
    title_Q1: "Rajasthan Royals",
    logo_Q1: "/img/flags/RR.png",

    time: {
      date: "17th May",
      time: "08:00 PM",
    },

    team_Q2: "PBKS",
    title_Q2: "Punjab Kings",
    logo_Q2: "/img/flags/punjab.png",
  },
  {
    team_Q1: "RR",
    title_Q1: "Rajasthan Royals",
    logo_Q1: "/img/flags/RR.png",

    time: {
      date: "17th May",
      time: "08:00 PM",
    },

    team_Q2: "PBKS",
    title_Q2: "Punjab Kings",
    logo_Q2: "/img/flags/punjab.png",
  },
  {
    team_Q1: "RR",
    title_Q1: "Rajasthan Royals",
    logo_Q1: "/img/flags/RR.png",

    time: {
      date: "17th May",
      time: "08:00 PM",
    },

    team_Q2: "PBKS",
    title_Q2: "Punjab Kings",
    logo_Q2: "/img/flags/punjab.png",
  },
];
export const teamOneData = [
  {
    id: 1,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "batter",
  },
  {
    id: 2,

    selected: false,
    name: "Ajinkya Rahane",
    correctionPoint: "100",
    wrongPoint: "15",
    playerType: "batter",
  },
  {
    id: 3,
    selected: false,
    name: "Shivam Dube",
    correctionPoint: "100",
    wrongPoint: "40",
    playerType: "batter",
  },
  {
    id: 4,
    selected: false,
    name: "Ranvindra Jadeja",
    correctionPoint: "120",
    wrongPoint: "30",
    playerType: "allrounder",
  },
  {
    id: 5,
    selected: false,
    name: "Daryl Mitchell",
    correctionPoint: "125",
    wrongPoint: "35",
    playerType: "allrounder",
  },
  {
    id: 6,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "allrounder",
  },
  {
    id: 7,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "batter",
  },
  {
    id: 8,
    selected: false,
    name: "Ajinkya Rahane",
    correctionPoint: "100",
    wrongPoint: "15",
    playerType: "batter",
  },
  {
    id: 9,
    selected: false,
    name: "Shivam Dube",
    correctionPoint: "100",
    wrongPoint: "40",
    playerType: "batter",
  },
  {
    id: 10,
    selected: false,
    name: "Ranvindra Jadeja",
    correctionPoint: "120",
    wrongPoint: "30",
    playerType: "allrounder",
  },
  {
    id: 11,
    selected: false,
    name: "Daryl Mitchell",
    correctionPoint: "125",
    wrongPoint: "35",
    playerType: "allrounder",
  },
  {
    id: 12,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "allrounder",
  },
];
export const teamTwoData = [
  {
    id: 1,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "batter",
  },
  {
    id: 2,

    selected: false,
    name: "Ajinkya Rahane",
    correctionPoint: "100",
    wrongPoint: "15",
    playerType: "batter",
  },
  {
    id: 3,
    selected: false,
    name: "Shivam Dube",
    correctionPoint: "100",
    wrongPoint: "40",
    playerType: "batter",
  },
  {
    id: 4,
    selected: false,
    name: "Ranvindra Jadeja",
    correctionPoint: "120",
    wrongPoint: "30",
    playerType: "allrounder",
  },
  {
    id: 5,
    selected: false,
    name: "Daryl Mitchell",
    correctionPoint: "125",
    wrongPoint: "35",
    playerType: "allrounder",
  },
  {
    id: 6,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "allrounder",
  },
  {
    id: 7,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "batter",
  },
  {
    id: 8,
    selected: false,
    name: "Ajinkya Rahane",
    correctionPoint: "100",
    wrongPoint: "15",
    playerType: "batter",
  },
  {
    id: 9,
    selected: false,
    name: "Shivam Dube",
    correctionPoint: "100",
    wrongPoint: "40",
    playerType: "batter",
  },
  {
    id: 10,
    selected: false,
    name: "Ranvindra Jadeja",
    correctionPoint: "120",
    wrongPoint: "30",
    playerType: "allrounder",
  },
  {
    id: 11,
    selected: false,
    name: "Daryl Mitchell",
    correctionPoint: "125",
    wrongPoint: "35",
    playerType: "allrounder",
  },
  {
    id: 12,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "allrounder",
  },
];

export const teamThreeData = [
  {
    id: 1,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "batter",
  },
  {
    id: 2,

    selected: false,
    name: "Ajinkya Rahane",
    correctionPoint: "100",
    wrongPoint: "15",
    playerType: "batter",
  },
  {
    id: 3,
    selected: false,
    name: "Shivam Dube",
    correctionPoint: "100",
    wrongPoint: "40",
    playerType: "batter",
  },
  {
    id: 4,
    selected: false,
    name: "Ranvindra Jadeja",
    correctionPoint: "120",
    wrongPoint: "30",
    playerType: "allrounder",
  },
  {
    id: 5,
    selected: false,
    name: "Daryl Mitchell",
    correctionPoint: "125",
    wrongPoint: "35",
    playerType: "allrounder",
  },
  {
    id: 6,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "allrounder",
  },
  {
    id: 7,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "batter",
  },
  {
    id: 8,
    selected: false,
    name: "Ajinkya Rahane",
    correctionPoint: "100",
    wrongPoint: "15",
    playerType: "batter",
  },
  {
    id: 9,
    selected: false,
    name: "Shivam Dube",
    correctionPoint: "100",
    wrongPoint: "40",
    playerType: "batter",
  },
  {
    id: 10,
    selected: false,
    name: "Ranvindra Jadeja",
    correctionPoint: "120",
    wrongPoint: "30",
    playerType: "allrounder",
  },
  {
    id: 11,
    selected: false,
    name: "Daryl Mitchell",
    correctionPoint: "125",
    wrongPoint: "35",
    playerType: "allrounder",
  },
  {
    id: 12,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "allrounder",
  },
];

export const teamFourData = [
  {
    id: 1,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "batter",
  },
  {
    id: 2,

    selected: false,
    name: "Ajinkya Rahane",
    correctionPoint: "100",
    wrongPoint: "15",
    playerType: "batter",
  },
  {
    id: 3,
    selected: false,
    name: "Shivam Dube",
    correctionPoint: "100",
    wrongPoint: "40",
    playerType: "batter",
  },
  {
    id: 4,
    selected: false,
    name: "Ranvindra Jadeja",
    correctionPoint: "120",
    wrongPoint: "30",
    playerType: "allrounder",
  },
  {
    id: 5,
    selected: false,
    name: "Daryl Mitchell",
    correctionPoint: "125",
    wrongPoint: "35",
    playerType: "allrounder",
  },
  {
    id: 6,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "allrounder",
  },
  {
    id: 7,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "batter",
  },
  {
    id: 8,
    selected: false,
    name: "Ajinkya Rahane",
    correctionPoint: "100",
    wrongPoint: "15",
    playerType: "batter",
  },
  {
    id: 9,
    selected: false,
    name: "Shivam Dube",
    correctionPoint: "100",
    wrongPoint: "40",
    playerType: "batter",
  },
  {
    id: 10,
    selected: false,
    name: "Ranvindra Jadeja",
    correctionPoint: "120",
    wrongPoint: "30",
    playerType: "allrounder",
  },
  {
    id: 11,
    selected: false,
    name: "Daryl Mitchell",
    correctionPoint: "125",
    wrongPoint: "35",
    playerType: "allrounder",
  },
  {
    id: 12,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "allrounder",
  },
];

export const teamFiveData = [
  {
    id: 1,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "batter",
  },
  {
    id: 2,

    selected: false,
    name: "Ajinkya Rahane",
    correctionPoint: "100",
    wrongPoint: "15",
    playerType: "batter",
  },
  {
    id: 3,
    selected: false,
    name: "Shivam Dube",
    correctionPoint: "100",
    wrongPoint: "40",
    playerType: "batter",
  },
  {
    id: 4,
    selected: false,
    name: "Ranvindra Jadeja",
    correctionPoint: "120",
    wrongPoint: "30",
    playerType: "allrounder",
  },
  {
    id: 5,
    selected: false,
    name: "Daryl Mitchell",
    correctionPoint: "125",
    wrongPoint: "35",
    playerType: "allrounder",
  },
  {
    id: 6,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "allrounder",
  },
  {
    id: 7,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "batter",
  },
  {
    id: 8,
    selected: false,
    name: "Ajinkya Rahane",
    correctionPoint: "100",
    wrongPoint: "15",
    playerType: "batter",
  },
  {
    id: 9,
    selected: false,
    name: "Shivam Dube",
    correctionPoint: "100",
    wrongPoint: "40",
    playerType: "batter",
  },
  {
    id: 10,
    selected: false,
    name: "Ranvindra Jadeja",
    correctionPoint: "120",
    wrongPoint: "30",
    playerType: "allrounder",
  },
  {
    id: 11,
    selected: false,
    name: "Daryl Mitchell",
    correctionPoint: "125",
    wrongPoint: "35",
    playerType: "allrounder",
  },
  {
    id: 12,
    selected: false,
    name: "Ruturaj Gaikwad",
    correctionPoint: "85",
    wrongPoint: "20",
    playerType: "allrounder",
  },
];
export const profileOptionsData = [
  {
    title: "My info & Settings",
    icon: <SettingsIcon />,
    link: "/settings",
  },

  {
    title: "Transactions",
    icon: <TransactionIcon />,
    link: "/transactions",
  },
  {
    title: "Refer and Earn",
    icon: <ReferIcon />,
    link: "/transactions",
  },
  {
    title: "Help and Support",
    icon: <HelpSupportIcon />,
    link: "/help-and-support",
  },

  {
    title: "How to Play",
    icon: <HowToPlayIcon />,
    link: "/how-to-play",
  },

  // {
  //   title: "FAQs",
  //   icon: <FAQIcon />,
  //   link: "/faq",
  // },

  {
    title: "Privacy Policy",
    icon: <PrivacyPolicyIcon />,
    link: "/privacy-policy",
  },

  {
    title: "Terms and Conditions",
    icon: <TermsCondition />,
    link: "/terms-and-conditions",
  },
];
